#!/bin/sh

# Start an LSP server for Clojure using clj-kondo

# Download the clj-kondo-lsp-server-standalone.jar from
# https://github.com/borkdude/clj-kondo/releases/
# Save jar to the path in the java command line below,
# or update the path to your preferred location.

# Example Emacs configuration in practicalli/spacemacs.d
# https://github.com/practicalli/spacemacs.d/

java -jar ~/.local/bin/clj-kondo-lsp-server-2021.03.31-standalone.jar

